logging:
  file.name: logs/app.log
  pattern:
    console: "%blue(%d) %highlight(%-5level) %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    com.valantic.sti: DEBUG
