spring:
  datasource:
    mockserver:
      url: jdbc:h2:file:./data/test.db # jdbc:h2:mem:testdb
      username: sa
      password: password
      driverClassName: org.h2.Driver # oracle.jdbc.OracleDriver, org.postgresql.Driver
  jpa:
    # database: default # let Spring autodetect different SQL dialects of each datasource
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
#  task:
#    scheduling:
#      pool:
#        size: 2

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%blue(%d) %highlight(%-5level) %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    com.valantic.sti: DEBUG

mockserver:
  enabled: false
  rate:
    database: PT5S
