# simple
mail.hostname: host@mail.com
mail.port: 9000
mail.from: mailer@mail.com

# list
mail.defaultRecipients: [
  admin@mail.com,
  owner@mail.com
]

# map
mail.additionalHeaders: {
  redelivery: true,
  secure: true
}

# object (record)
mail:
  credentials:
    username: john
    password: password
    authMethod: SHA1

# bean
item:
  a: Gerrit
  b: 9
  c: false

# conversion
conversion:
  timeInDefaultUnit: 10
  timeInNano: 9ns
  sizeInDefaultUnit: 300
  sizeInGB: 2GB # B, KB, MB, GB, and TB
  sizeInTB: 4
  employee: john,2000

# @Value
person:
  firstname: Gerrit

spring:
  config:
    import: optional:secrets.properties
